name: c-ocgeo CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install libcurl
      run: sudo apt-get install libcurl-dev
    - name: make
      run: make
    - name: make test
      run: make test
